CREATE TABLE IF NOT EXISTS CityInfo (
  ZIPCODE VARCHAR(20) NOT NULL,
  CITY VARCHAR(50),
  PRIMARY KEY (ZIPCODE)
);

CREATE TABLE IF NOT EXISTS InfoEntity (
  ID INT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR (255),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Address (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_A INT NOT NULL,
  STREET VARCHAR(255) NOT NULL,
  ADDITIONALINFO VARCHAR(255),
  ZIPCODE_A VARCHAR(50),
  PRIMARY KEY (ID),
  FOREIGN KEY (ZIPCODE_A) REFERENCES CityInfo(ZIPCODE),
  FOREIGN KEY (ID_A) REFERENCES InfoEntity(ID)
);

CREATE TABLE IF NOT EXISTS Phone (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_P INT NOT NULL,
  PHONENUM VARCHAR(50),
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_P) REFERENCES InfoEntity(ID)
);

CREATE TABLE IF NOT EXISTS Company (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_C INT NOT NULL,
  COMPANYNAME VARCHAR(255),
  DESCRIPTION VARCHAR(500),
  CVR VARCHAR(255),
  NUMEMPLOYEES INT NOT NULL,
  MARKETVALUE VARCHAR (255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_C) REFERENCES InfoEntity(ID)
);

CREATE TABLE IF NOT EXISTS Person (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_P INT NOT NULL,
  FIRSTNAME VARCHAR(255),
  LASTNAME VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_P) REFERENCES InfoEntity(ID)
);

CREATE TABLE IF NOT EXISTS Hobby (
  ID INT NOT NULL AUTO_INCREMENT,
  ID_H INT NOT NULL,
  HOBBYNAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  PRIMARY KEY(ID),
  FOREIGN KEY (ID_H) REFERENCES Person(ID)
);

COMMIT;